name: config_change_alert

on:
  push:
    branches: 
      - main
#     paths:
#       - index.html
#       - templates/NOTES.txt

#   pull_request:
#     branches: 
#       - main
#     paths:
#       - .github/workflows/alert.yaml
#       - index.html
#       - templates/NOTES.txt
      
jobs:
  COnfig_alert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          FILES: |
              - index.html
              - templates/NOTES.txt
              - .github/workflows/alert2.yaml
              
      - run: echo '${{ env.GIT_DIFF }}'
