name: config

on:
  push:
    branches: 
      - main

      
jobs:
  COnfig_alert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          FILES: |
              - index.html
              - templates/NOTES.txt
              - .github/workflows/alert2.yaml
              
      - name: diff
        run: |
           echo '${{ env.GIT_DIFF }}' 
           git diff .github/workflows/alert2.yaml >> dif.log 
           cat dif.log
      
