name: config_change_alert

on:
  push:
   branches: 
     - staging
   paths:
      - .github/workflows/alert.yaml
      - index.html
      - templates/NOTES.txt
  
  pull_request:
    branches: 
      - main
    types:
    - closed
    paths:
      - .github/workflows/alert.yaml
      - index.html
      - templates/NOTES.txt
   
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v18.4
             
      - name: Run step when a 0chain.yaml file changes
        if: contains(steps.changed-files.outputs.modified_files, 'index.html')
        run: |
          echo "Your 0chain.yaml file has been modified."
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Your index.html config file has been modified."}' ${{ secrets.CHANNEL_WEBHOOK_URL }}
