name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitpipeline:$(date +%s)
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         logout: true
   
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitpipeline:latest

    - uses: actions/checkout@v2
    - name: Run Kubernetes tools
      uses: grebois/kube-tools@v1.5.2
      with:
          kubectl: 1.18.2
          helmv3: 3.2.1
          kubeseal: 0.12.5
          helm: 2.16.7
          kubeaudit: 0.11.5
          command: |
            pwd 
            ls -la
            helmv3 install npipeline .  | kubeval --strict
            helmv3 list
   
