name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

 Build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitpipeline:$(date +%s)
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         logout: true
   
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitpipeline:latest
    
 Deploy:
   
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: tanmancan/action-setup-ssh-agent-key@1.0.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY_ONE }}
      # Key for a first server
      run: ssh -T ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }} "helm version"
           echo $WELCOME
    
 
