name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitpipeline:$(date +%s)
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         logout: true
   
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitpipeline:latest
  
  deploy:   
  
     name: Deploy to Kubernetes
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - name: Prep helm chart
         run: |
             helm list
         
   
   
     
 
