name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitpipeline:$(date +%s)
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         logout: true
   
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitpipeline:latest
   
    - name: Helm Chart Testing Helm 3
        # You may pin to the exact commit or the version.
        # uses: HexF/chart-testing-action@b4a4fbe84c7a7b83e4e106d1c954048e5c5cfb2d
        uses: HexF/chart-testing-action@v3.0.1
        with:
        # The chart-testing Docker image to use (default: quay.io/helmpack/chart-testing:v2.4.0)
        image: ${{ secrets.DOCKERHUB_USERNAME }}/gitpipeline
        # The relative path to the chart-testing config file
        config: 
        # The chart-testing command to run
        command: 
         # The path to the kube config file
    kubeconfig: # optional
   
