name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

 Build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitpipeline:$(date +%s)
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         logout: true
   
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitpipeline:latest
    
 Deploy:
   
    needs: Build
    runs-on: ubuntu-latest
    steps: 
    - name: Helm Publisher
      # You may pin to the exact commit or the version.
      # uses: stefanprodan/helm-gh-pages@f1701eb82e4d4b82016e7965501c8b6d79feaec9
      uses: stefanprodan/helm-gh-pages@v1.4.1
      with:
        # GitHub token
        token: ${{ secrets.GIT_TOKEN }}
        # The charts directory, defaults to `charts`
        charts_dir: chart
        # The GitHub Pages URL, defaults to `https://<OWNER>.github.io/<REPOSITORY>`
        charts_url: https://vinayakgautam-vg.github.io/gitpipeline/
        # The GitHub user or org that owns this repository, defaults to `GITHUB_REPOSITORY`
        owner: vinayakgautam-vg
        # The GitHub repository name, defaults to `GITHUB_REPOSITORY`
        repository: gitpipeline
        # The branch to publish charts, defaults to `gh-pages`
        branch: helm-gitpipeline
        # The Helm CLI version
        helm_version: 3.7.1
