name: merge
on:
  push:
   branches: 
     - main 
  pull_request:
    types: [closed]
    branches: 
      - main
   
jobs:
  test:
    runs-on: ubuntu-18.04  
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.4
        with:
          files: |
             index.html
             
      - name: Run step if only the files listed above change
        if: steps.changed-files-specific.outputs.only_changed == 'true'
        run: |
          echo "Only $files listed above have changed."
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Your index.html file has been modified. View the test results on Github: https://github.com/0chain/system_test/actions/runs/${{ github.run_id }}"}' ${{ secrets.CHANNEL_WEBHOOK_URL }}
