name: Merge Alert 

on:
  push:
   branches: 
     - main
  pull_request:
   
jobs:
  test:
    runs-on: ubuntu-18.04  
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            index.html
            templates/NOTES.txt

      - name: Run step if any of the listed files above change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "0chain config maps updated ."
          curl -X POST -H 'Content-type: application/json' --data '{"text":"0chain config map updated."}' ${{ secrets.CHANNEL_WEBHOOK_URL }}
      
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v18.4   
     
#       - name: Run step when a file changes
#         if: contains(steps.changed-files.outputs.modified_files, 'templates/NOTES.txt')
#         run: |
#           echo "Your file has been modified."
#           curl -X POST -H 'Content-type: application/json' --data '{"text":"Your templates/NOTES.txt config file has been modified."}' ${{ secrets.CHANNEL_WEBHOOK_URL }}

      - name: get docker image name
        id: get_info
        run: |
         if [[ "${{github.ref}}" == refs/pull/* ]]; then
          tag=${GITHUB_REF/\/merge/}
          echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
         else
          echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
         fi
         echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
         echo "SHA=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}')" >> $GITHUB_ENV
      
      - name: image name 
        id: image_name
        run: |
         SHORT_SHA=$(echo ${{ env.SHA }} | head -c 8)
         echo "$TAG-$SHORT_SHA" > name 
         
     
      - name: Run image update command  
        id: image_updated
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"Sharder/Miner: ${{ steps.image_name.name }}"}' ${{ secrets.CHANNEL_WEBHOOK_URL }}
     
     
  server:
    needs: test
    runs-on: ubuntu-18.04  
    steps:   
      - name: Run step when a file changes
        run: |
          echo "Your file has been modified."
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Sharder/Miner:$TAG-$SHORT_SHA image updated on network name."}' ${{ secrets.CHANNEL_WEBHOOK_URL }}
