name: update values file 

on:
  push:
   branches: 
     - main
  pull_request:
   
jobs:
  test:
    runs-on: ubuntu-18.04  
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
 
      - name: Get config map changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            index.html
            templates/NOTES.txt
 
      - name: update config map command 
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "0chain config maps updated ."
          cat <<\EOF > val.yaml
          i
          am
          testing
          config
          map
          in
          git
          action
          in
          task
          EOF
      
      - name:  update values.yaml
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
           echo "updated values.yaml."
           sed -i -e 's/^/    /' index.html &&  sed -i '3  r index.html' val.yaml
           echo "$(<val.yaml)"
           
      - name: Pushes to another repository
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          git config --global user.email "iamvinigautam@gmail.com"
          git config --global user.name "vinayakgautam-vg"
          git remote set-url origin https://github.com/vinayakgautam-vg/npipeline-helm.git
          git add val.yaml
          git branch -M master
          git commit -m "update config"
          git status
          git branch 
          cat .git/config
          curl -X POST -H 'Content-type: application/json' --data '{"text":"0chain config map updated."}' ${{ secrets.CHANNEL_WEBHOOK_URL }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: master     
#       - name: Pushes to another repository
#         if: steps.changed-files-specific.outputs.any_changed == 'true'
#         uses: cpina/github-action-push-to-another-repository@main
#         env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#         with:
#           source-directory: '/home/runner/work/gitpipeline/gitpipeline/val.yaml'
#           destination-github-username: 'vinayakgautam-vg'
#           destination-repository-name: 'npipeline-helm'
#           user-email: iamvinigautam@gmail.com
# #           target-branch: master
#             git branch -M master
#             git push -u origin master 
# git push -f origin master --prune https://token:${{ secrets.API_TOKEN_GITHUB }}@github.com/vinayakgautam-vg/npipeline-helm.git
